[build]
  publish="./build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "0"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=0"
    Content-Security-Policy = "upgrade-insecure-requests"
